### ISSUE TITLE
Polls don't appear in the focused post

### ISSUE THREAD

**Issue by Freeplayg** [TheEssem/mastodon#24] opened 2024-09-14 16:38 UTC
### Steps to reproduce the problem

1. Find a post with a poll
2. Open it

### Expected behaviour

Poll is visible

### Actual behaviour

poll isn't there

### Detailed description

[Screencast from 2024-09-14 12-35-20.webm](https://github.com/user-attachments/assets/01a03391-4227-4045-aee2-db86d536ebb6)

### Mastodon instance

wetdry.world

### Mastodon version

v4.3.0-beta.1+chuckya

### Browser name and version

Chromium 128.0.6613.137

### Operating system

fedora silverblue

**Comment by TheEssem** [comment] 2024-09-14 20:11
It appears this was caused by mastodon/mastodon#31766; for some reason, much of the poll-related functionality in DetailedStatus was removed. I'm not sure if this was intentional or not, or if they plan to add it back before the full 4.3.0 release.

**Comment by Freeplayg** [comment] 2024-09-16 21:57
i seem to also be able to click on already-opened posts which leads to /undefined so i think this is very broken D:

**Comment by TheEssem** [comment] 2024-12-01 15:10
Looks like this was fixed in glitch-soc#2857, closing.

**Closed by TheEssem** 2024-12-01 15:10 UTC
Labels: bug
